[phases.build]
cmds = [
    "bundle install --without development test",
    "mkdir -p tmp log",
    "chmod -R 777 tmp log"
]

[phases.start]
cmd = "bundle exec rails server -p $PORT -b 0.0.0.0"

[variables]
BUNDLE_WITHOUT = "development:test"
RAILS_ENV = "production"
RAILS_LOG_TO_STDOUT = "true"
RAILS_SERVE_STATIC_FILES = "true"